variables:
  GIT_DEPTH: "0"
  REPO_URL: "http://$GIT_USER:$GIT_USER_CLAVE@git.mct.com.co/frontend/switrans_2_0.git"
  WORK_DIR: "/home/docker/front-end/proyecto-switrans-2/switrans_2_0"

before_script:
  - DEVELOPER=$(echo $GITLAB_USER_LOGIN | tr '.' '-')

stages:
  - lints
  - review
  - build
  - deploy

lints:
  stage: lints
  script:
    - cd $WORK_DIR && echo $WORK_DIR
    - echo $CI_COMMIT_BRANCH
    - git remote set-url origin $REPO_URL
    - git fetch --all
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git pull origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - STAGE=analyze docker compose -f docker-compose-$DEVELOPER.yml build
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

build-merge-request:
  stage: review
  script:
    - cd $WORK_DIR && echo $WORK_DIR
    - echo "Construyendo con los cambios del Merge Request..."
    - git fetch --all
    - git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git log --oneline -n 5
    - STAGE=build docker compose -f docker-compose-$DEVELOPER.yml build
    - STAGE=runner docker compose -f docker-compose-$DEVELOPER.yml up -d --build
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

build:
  stage: build
  script:
    - cd $WORK_DIR && echo $WORK_DIR
    - git checkout develop
    - git pull origin develop
    - git status
    - git log --oneline -n 15
    - docker compose -f docker-compose-production.yml up -d --build
    - echo consultar en http://192.168.102.18:3000
    - echo "Finalizó con Éxito!!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploy-release:
  stage: deploy
  script:
    - echo "Desplegando la aplicación..."
    - |
      ssh root@192.168.102.21 "
        cd $WORK_DIR && echo $WORK_DIR &&
        git checkout develop &&
        git pull origin develop &&
        docker compose -f docker-compose-production.yml up -d --build &&
        echo 'Finalizó Despliegue a Prepo' &&
        echo 'Consultar en http://192.168.102.21:3000'
      "
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: manual

