image: erneyvargasdev/flutter-image:3.22.0

variables:
  GIT_DEPTH: "0"

stages:
  - lints
  - deploy

lints:
  stage: lints
  script:
    - cd /home/docker/front-end/proyecto-switrans-2/switrans_2_0
    - docker exec switrans2-flutter /bin/bash -c "flutter pub get && flutter analyze"

deploy:
  stage: deploy
  script:
    - cd /home/docker/front-end/proyecto-switrans-2/switrans_2_0
    - "credeciales=\"$GIT_USER:$GIT_USER_CLAVE@\""
    - "ruta=$(git config --get remote.origin.url | sed \"s/:\\/\\//:\\/\\/$credeciales/g\")"
    - "echo $ruta"
    - "git checkout develop"
    - "git pull $ruta develop"
    - "git status"
    - "git log --oneline -n 15"
    - docker exec switrans2-flutter /bin/bash -c "flutter clean && flutter pub get && flutter build web --wasm --no-tree-shake-icons"
    - rm -fR ../server/web/
    - cp -r build/web/ ../server/
    - echo "Finalizo con Exito!!"
    
  only:
    - develop
