variables:
  GIT_DEPTH: "0"
  REPO_URL: "http://$GIT_USER:$GIT_USER_CLAVE@git.mct.com.co/frontend/switrans_2_0.git"
  WORK_DIR: "/home/docker/front-end/proyecto-switrans-2/switrans_2_0"

stages:
  - lints
  - review
  - deploy

lints:
  stage: lints
  script:
    - cd $WORK_DIR
    - docker exec switrans2-flutter /bin/bash -c "flutter pub get && flutter analyze"
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

build-merge-request:
  stage: review
  script:
    - cd $WORK_DIR
    - git log --oneline -n 15
    - echo "Construyendo con los cambios del Merge Request..."
    - echo $CI_COMMIT_BRANCH
    - echo $CI_MERGE_REQUEST_ID
    - git remote set-url origin $REPO_URL
    - git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - docker exec switrans2-flutter /bin/bash -c "flutter clean && flutter pub get && flutter build web --wasm --no-tree-shake-icons"
    - docker compose down
    - docker compose up -d
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

deploy:
  stage: deploy
  script:
    - cd $WORK_DIR
    - git checkout develop
    - git pull origin develop
    - git status
    - git log --oneline -n 15
    - docker exec switrans2-flutter /bin/bash -c "flutter clean && flutter pub get && flutter build web --wasm --no-tree-shake-icons"
    - rm -rf ../server/web/
    - cp -r build/web/ ../server/
    - echo "Finalizó con Éxito!!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  when: manual # Manualmente en la rama develop