image: cirrusci/flutter:latest

stages:
  - lints
  - tests
  - build
  - deploy

before_script:
  - /home/evargas/fvm/default/bin/flutter pub get

lints:
  stage: lints
  script:
    - /home/evargas/fvm/default/bin/flutter analyze

tests:
  stage: tests
  script:
    - flutter test

build:
  stage: build
  script:
    - flutter build web

deploy:
  stage: deploy
  script:
    - cp -r build/web public
    - git push origin live