image: erneyvargasdev/flutter-image:3.22.0

variables:
  GIT_DEPTH: "0"

stages:
  - lints
  - deploy

lints:
  stage: lints
  script:
    - cd /home/erneyvargas/docker/switrans_2_0
    - docker container run -v $(pwd):/app erneyvargasdev/flutter-image:3.22.0 flutter pub get flutter analyze

deploy:
  stage: deploy
  script:
    - cd /home/erneyvargas/docker/switrans_2_0
    - git pull http://$GIT_USER:$GIT_USER_CLAVE@git.mct.com.co develop
    - cd /home/erneyvargas/docker/switrans_2_0 && flutter build web
    
  only:
    - develop
