services:
  flutter:
    image: flutter-image:3.22.0
    container_name: switrans2-flutter
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "tail -f /dev/null"
    healthcheck:
      test: echo "Flutter container is running"
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      macvlan_virbr_102SRV:
        ipv4_address: 192.168.102.100

  mongo:
    image: mongo:6.0
    container_name: switrans2-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/../db/mongo_data:/data/db
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      macvlan_virbr_102SRV:
        ipv4_address: 192.168.102.101

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: switrans2-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${PWD}/../db/pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      macvlan_virbr_102SRV:
        ipv4_address: 192.168.102.102

  node:
    image: node:18
    container_name: switrans2-node
    volumes:
      - ${PWD}/../:/app
    working_dir: /app/server
    restart: unless-stopped
    command: >
      sh -c "cp -r ../switrans_2_0/build/web/ ./ && cp -r ../switrans_2_0/web/node_server/. ./ && npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - pocketbase
    healthcheck:
      test: curl -f http://localhost:3002 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      macvlan_virbr_102SRV:
        ipv4_address: 192.168.102.103