FROM ubuntu:22.04

RUN apt update -y && apt upgrade -y &&  \
    apt install -y curl git unzip openjdk-8-jdk wget clang cmake ninja-build pkg-config libgtk-3-dev \
    xz-utils zip libglu1-mesa iputils-ping vim

ARG USER=root
USER $USER
WORKDIR /home/$USER

RUN git clone -b 3.22.3 https://github.com/flutter/flutter.git
ENV PATH="/home/root/flutter/bin:${PATH}"