services:

  switrans2-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    container_name: switrans2-server
    working_dir: /app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - pocketbase
    healthcheck:
      test: curl -f http://localhost:${PORT} || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  pocketbase:
    image: pocketbase:0.22.20
    container_name: switrans2-pocketbase
    restart: unless-stopped
    ports:
      - "${PORT_PB}:8090"
    volumes:
      - ./../db/pocketbase/pb_data:/pb/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT_PB}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge

