services:
  flutter:
    image: flutter-image
    container_name: flutter_container
    
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        flutter pub get &&
        tail -f /dev/null
      "
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    #network_mode: host 

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /home/evargas/development/frontend/web/projects_flutter/switrans_2_0/db/pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

